string AUTO = "AUTO"              # reliability
string RELIABLE ="RELIABLE"       # reliability
string UNRELIABLE = "UNRELIABLE"  # reliability
string NORMAL = "NORMAL"          # robustness, priority
string ROBUST = "ROBUST"          # robustness
string URGENT = "URGENT"          # priority
string HIGH = "HIGH"              # priority
string LOW = "LOW"                # priority
string IDLE = "IDLE"              # priority
float32 UNDEFINED = -1            # ttl
float32 MAILBOX = 0               # ttl

uint8[] data
uint16 to 0
uint8 protocol 0
string reliability "AUTO"
string robustness "NORMAL"
string priority "NORMAL"
float32 ttl -1
bool shortcircuit true
string route ""
---
bool agree
string id
string reason
